### ISSUE TITLE
Unable to configure debug configuration in Atom (Windows 10)

### ISSUE THREAD

**Issue by michaelvlaar** [lloiser/go-debug#130]
Hi,

I'm trying to configure command-line arguments when starting a debug session in Atom (I'm using Windows 10).

I've added the configuration file `debug-configuration.json` to the root of my Go project, and added:

```js
{
  "configurations": [
    {
      "name": "Debug myapp",
      "mode": "debug",
      "cwd": "${workspaceRoot}/myapp",
      "args": ["--config=config.ini"]
    }
  ]
}
```

I've configured the relative path `debug-configuration.json` in the Atom go-debug as the `Configuration File`. 

But when I restart Atom, go-debug gives the following warning:

```
Please make sure the configuration file 'C:\Users\<username>\Documents\Go\src\myapp\debug-configuration.json' exists
```

I have verified that the path is correct and the file exists, but still the configuration is not picked up.

Does anyone else experience this warning?

FYI, The (default) `debug` and `test` configuration works fine.

Thanks,
Michael

**Comment by lloiser** [comment]
You have a syntax error in your JSON: there is a trailing `,` after the `args` array which is invalid.
But this is not the problem because this would lead to another error message to pop up :)

Please open the developer tools of atom using the `Toggle Dev Tools` command from the command palette. A new panel or window should open. Open the `Console` tab. In this console there should be one or many messages that have `go-debug` in it. Pls copy/paste all these message here.

**Comment by michaelvlaar** [comment]
Hi,

(The JSON error was actually a typo, thanks for the heads up)

I got the following console message:

```
delve-configuration.js:110
go-debug Failed to load configuration file 'C:\Users\<username>\Documents\Go\src\myapp\debug-configuration.json'. TypeError: (0 , _atom.watchPath) is not a function at main.js:107
```

**Comment by lloiser** [comment]
pls update atom to the latest version 1.23

**Comment by michaelvlaar** [comment]
I didn't notice there was a new version (no automatic update).
I've updated Atom from version `1.19` to `1.23.3`, the issue is now resolved.

Thanks for the quick help 👍
