### ISSUE TITLE
Allow Debug Window To Be Closed / Hidden

### ISSUE THREAD

**Issue by joefitzgerald** [lloiser/go-debug#39]
The debug window occupies a not-insignificant amount of screen space, and it does so even when you're not working with `go` code. It would be nice to:
- Allow the window to be closed / hidden
- Prevent initialization of the window until debugging is started for the first time (e.g. perhaps by invoking a command / menu item)
- Prevent initialization of the window until a `.go` file is opened (look at `grammar-used` activation hooks https://github.com/atom/atom/pull/7638 / https://github.com/atom/atom/pull/9527)

**Comment by lloiser** [comment]
you can already resize and toggle (`ctrl-k ctrl-g` / `cmd-k cmd-g`) the debug window
the other two points seem reasonable, I will give them a try.

**Comment by joefitzgerald** [comment]
Thanks! That you can toggle the window is not obvious. Perhaps add an `x` in the style of a tab close button, to make it more obvious?

**Comment by grawlinson** [comment]
The resize+toggle needs to be made explicitly obvious. I know it's in README.md, but I only really figured it out by looking at this issue.

**Comment by cstockton** [comment]
Hi there, I have some feedback for ya because it's clear you put a good bit of effort into this and I think it has good potential. I'm rather particular about my environment and maybe others may share some of my opinions.

- It takes up a huge amount of real estate that was a bit of a put-off right off the bat. I use a 4k monitor with 2 panes for code and a terminal beside it and it's just big enough to restrict my preferred line length. In this pane there is two input boxes and the 4 expandable which are always empty leaving about 80% of prime real estate in my IDE completely wasted.

- I'm not sure why the expandable Goroutines, stacktrace, etc are always empty.. it would be cool to see some of that data in the UI. **Suggestion: perhaps when all of that info is empty it could give a visual cue by making it partially transparent to seem "inactive" and expand it when data is available for the first time to train the user on what action activates them (I Haven't found out what does yet).**

- I wanted to give it a fair shot though before I closed it so I opened a Go project and clicked "test" .. nothing happened and I didn't see any output or data in the expandable so I was a bit confused. Same thing when I clicked debug.. I knew the program had tests and had a main that could run.

- I didn't realize it at first.. not until I uninstalled it and realized it was coming back each time I opened my IDE and was starting to get a bit frustrated so was frantically searching for a close button or context menu. But I did finally see the plain white text at the bottom was a "button" to open a console.. using.. more real estate :- ) I think that output would be much better placed in an expandable box named "> Console" under "> Breakpoints". It may be my atom-dark theme/syntax contributing. **Suggestion: first time (or if more feasible as a first-pass every time) the user clicks "Test" open the console window and a visual cue on the "Toggle output panel" will train idiots like me who miss it.**

- Once I figured out where the console was and clicked test I noticed it ran "go test" which was cool and all but I have a program that will run go-test each time I save in a console already. In order to use this app it would need to run go-test each time I save, I rarely ever touch my mouse while working. Having an option for this would be cool or maybe a way to toggle the mode in the UI for when you didn't want to auto run tests.

- Clicking Test made sense, self describing.. but the Debug button left me a bit confused. Clicking on "Debug" causes some of my Main output to be spit out then it exits with a message "delve closed with code null" even though the program is still running (spins up net listener) and all the expendables stay empty.

- This is more of a **go-plus** @joefitzgerald thing.. So I wanted to uninstall it despite seeing that it could be useful simply because I saw no way to close it and I needed to start getting work done. This led to some actual irritation when I uninstalled and when I opened my IDE back up go-plus started reinstalling it. This was pretttttty silly, this specific plugin is very intrusive so updating your IDE/Plugins should not cause an infinite loop of `you must have this`. It doesn't seem to be integral to the core functions of go-plus since I use go-plus strictly for build/lint errors and formatting on save.

- I tried looking in **go-plus** plugin but it had no options to disable or change any auto update features. I've never fiddled much with go-plus, it kind of has always just worked.. I figured the auto-updates were placed in another package.. but `go-get` has no settings, `go-config` doesn't either and I just can't figure out how to make it stop this infinite install loop. I'm sure you have an option somewhere I just can't find it. It's a really bad user experience but rather than rage because your tool has been really awesome and you've put so much work into it I can't really be mad. Just going to leave this feedback.

- I understand having some separation for these packages, maybe it's easier to maintain and such.. but if you keep adding tools and auto installing and such it's going to get pretty overwhelming for an end user who wants to tweak basic settings, least from my perspective. It would maybe be nice if `go-config` had in it's settings a proxy to configure all other plugins that go-plus manages.. or do that in go-plus itself. Just a thought.

Please don't mistake this with any negative tone or anything personal, go-plus is a great tool and I could see go-debug being a good addition.. just might need a bit of UI/UX tweaks to make it a bit less intrusive when introduced to someone for the first time. It's hard to see that when you created it because there is an intimate familiarity with your work.

-Chris

**Comment by joefitzgerald** [comment]
This is really great feedback - thanks for providing it. I will be taking action of the go-plus front, but in the interim:

* You can go to go-debug package settings and toggle the Panel Initially Visible option. Also observe the keyboard shortcut for toggling it on / off
* You can disable the go-debug package and it will no longer be loaded; go-plus will also not re-enable it; this is functionally equivalent to uninstalling it but at the inconvenience of a small amount of disk space

I see you're also creating specific issues at go-plus (thanks) which I will address there.

In general it feels like we should change the default for "Panel Initially Visible" from true to false.

**Comment by joefitzgerald** [comment]
`v0.1.20` is released which changes the default for `Panel Initially Visible` to false.

**Comment by cstockton** [comment]
Thanks a lot for taking my feedback graciously, I use Go-plus every day and I think it's great. I'm sure go-debug will polish up nice.

**Comment by lloiser** [comment]
hey @cstockton, a lot has changed in the meanwhile and with [`go-debug` v1.4.0](https://github.com/lloiser/go-debug/releases/tag/v1.4.0) it also supports the new dock feature from atom. Check it out. Maybe this issue can then be finally closed 😁
