### ISSUE TITLE
Use 2nd debugger - https://github.com/mailgun/godebug

### ISSUE THREAD

**Issue by joefitzgerald** [lloiser/go-debug#4]
https://github.com/joefitzgerald/go-get

This would prevent part of #3.

**Comment by lloiser** [comment]
I don't think that this solves the problem entirely because getting the sources only isn't enough. You also have to build them using `make` (see https://github.com/derekparker/delve/tree/master/Documentation/installation)

Although I already use https://github.com/joefitzgerald/go-config to find the `dlv` so this shouldn't be any problem anymore.

**Comment by joefitzgerald** [comment]
Ahh yeah, good call. I wonder if it would be worth _also_ giving people an option of using [godebug](https://github.com/mailgun/godebug) since it _is_ go gettable? I know the feature sets don't match 1:1. but there is some shared functionality.

**Comment by lloiser** [comment]
Great idea, I will give it try as soon as I have some free time to play with it a bit.

**Comment by lloiser** [comment]
Update: have to fork it as it seems pretty "dead" (last commit in September 2015...) and is not really easy to integrate yet...

**Comment by pkieltyka** [comment]
personally, -1 on https://github.com/mailgun/godebug  .. its a nice idea, but I've never found it useful for any serious debugging.

**Comment by pkieltyka** [comment]
If the issue is getting this plugin to just plug-and-play, you could look at how IntelliJ pulls it off. Their go ide plugin supports delve right out of the box. I think they just package a pre-compiled binary with a cert for the system.

Otherwise, just link clearly to Delve install instructions until the Delve guys solve this problem

**Comment by batatababa** [comment]
Agreed on godebug not being good for serious debugging. I've been using it and it's better than nothing and quick to get going. It won't run if you have vendored dependencies which is a big deal.

**Comment by joefitzgerald** [comment]
Closing this, it appears `godebug` isn't actively maintained anymore. @jeremyschlatter, feel free to correct me if I am wrong.
