### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by italolelis** [lloiser/go-debug#49]
Hi guys,

I'm kind of new to use delve for debugging, so excuse em if I'm asking smth that doesn't make sense.
So I have a container that has a go application running... Is there a way to run the debugger in the container and see it in the editor?

Thank you so much for the help.

**Comment by wader** [comment]
I did some experiments and got go-debug to talk to delve running in a container. Here is what is needed to do:

- Run container with `--privileged`. Default docker filters trace syscalls used by delve
- Run container with `-v "$GOPATH:$GOPATH"` to have same paths on host and container, otherwise go-debug seems to get confused
- Run container with `-p 2345:2345` so that go-debug can talk to delve
- Create a wrapper `dlv` script on the host that is in `$PATH` (move away original binary is needed). It forwards `$GOPATH` and starts delve listening on any interface so that the port forward works
```
#!/bin/sh
exec docker exec -i <CONTAINER-ID-HERE> sh -c "cd $PWD && GOPATH=$GOPATH dlv debug --headless=true --listen=:2345 --log"
```

Run container (in my case `golang:1.7-onbuild`) with some dummy command to make it stay alive, use some shell, sleep etc and make sure delve is installed (`go get github.com/derekparker/delve/cmd/dlv`). Now start debugging in atom.

I noticed that delve does not exit when stop debugging in atom. But i guess the hard question is how to make something like this easy to use. Maybe support for custom dlv path is enough?

**Comment by lloiser** [comment]
Thanks for experimenting @wader! This is a nice workaround for now!
I'm currently in the middle of a rewrite and this contains configurations that also support things like connecting to a remotely running `dlv` (similar to what the go plugin of vscode already supports).

**Comment by lloiser** [comment]
It is possible to define [configurations](https://github.com/lloiser/go-debug#configuration) with the latest version (`v1.0.0`).
These configurations also include a `mode` to `connect` to a headless delve running somewhere else. Also add `host` and `port` to specify the (delve) endpoint.
