### ISSUE TITLE
delve exec support

### ISSUE THREAD

**Issue by ulrichSchreiner** [lloiser/go-debug#7]
hi,

it would be great to support the `exec` command from delve to debug a precompiled binary. i use `gb` to build my binaries so `dlv debug` does not work. 

And it would be a great idea to have debug-configurations like visualstudio-code, so that one can specifiy not only the binary to start but also arguments and environment variables.

i integrated this in my [vsc](https://github.com/ulrichSchreiner/vsc#debug-support) container and it would be great to have your plugin in my [atocker](https://github.com/ulrichSchreiner/atocker) container too.

**Comment by lloiser** [comment]
the exec button is rather easy to add so expect it to be available soon
the configs are on my todo list which unfortunately gets longer and longer, but I will give it a try anyway!

**Comment by lloiser** [comment]
it seems that this has to be postponed for now. There is a discussion with the other golang editor integrations on a single config file which is then used by each editor instead of having different configs for each editor

**Comment by lloiser** [comment]
Sorry for the late response... This is possible since `v1.0.0` of go-debug. Checkout the [README](https://github.com/lloiser/go-debug#configuration)  for more info.

Basically you have to create a file that contains the configurations and set the path to it in the go-debug setting "Configuration File". 

The configuration file should contain the following JSON:

```json
{
  "configurations": [
    {
      "name": "Exec",
      "mode": "exec",
      "program": "<path to the executable>"
    }
  ]
}
```
_note: you can also pass arguments or set environment variables using the `args` and `env` properties (checkout the [README](https://github.com/lloiser/go-debug#configuration) for more info)
